# Change these first
owner: dhedegaard # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: dhedegaard.dk
    url: https://www.dhedegaard.dk
  - name: culan.dk
    url: https://www.culan.dk
  - name: Poetracker
    url: https://poe.culan.dk
  - name: Poetracker (API)
    url: https://api-poe.culan.dk/data/negotiate
    method: POST
  - name: Pollen
    url: https://pollen.dhedegaard.dk
  - name: Youtube aggregator
    url: https://ut.dhedegaard.dk
  - name: Advent of Code 2020
    url: https://aoc2020.dhedegaard.dk
  - name: Advent of Code 2019
    url: https://aoc2019.dhedegaard.dk
  - name: Neversink downloader
    url: https://neversink.culan.dk
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dhedegaard.dk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "status.dhedegaard.dk"
  introMessage: Uptime monitoring for my various personal projects and websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
